// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'big': string;
  'commom': string;
  'container': string;
  'medium': string;
  'small': string;
  'title': string;
}
declare var cssExports: CssExports;
export = cssExports;
