// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'headerBg': string;
  'header_bg': string;
}
export const cssExports: CssExports;
export default cssExports;
